Param_Index_Dict = {
    "dt": [],
    "w": [],
    "discount_rate": [],
    "annual_co2_limit": ["Y"],
    "co2_price": ["Y"],
    "opex_cost_energy": ["CS", "Y"],
    "opex_cost_power": ["CS", "Y"],
    "capex_cost_power": ["CS", "Y"],
    "efficiency": ["CS"],
    "technical_lifetime": ["CS"],
    "cap_min": ["CS", "Y"],
    "cap_max": ["CS", "Y"],
    "cap_res_min": ["CS", "Y"],
    "cap_res_max": ["CS", "Y"],
    "availability_profile": ["CS", "T"],
    "technical_availability": ["CS"],
    "output_profile": ["CS", "T"],
    "max_eout": ["CS", "Y"],
    "min_eout": ["CS", "Y"],
    "out_frac_min": ["CS", "Y"],
    "out_frac_max": ["CS", "Y"],
    "in_frac_min": ["CS", "Y"],
    "in_frac_max": ["CS", "Y"],
    "spec_co2": ["CS"],
    "is_storage": ["CS"],
    "c_rate": ["CS"],
    "efficiency_charge": ["CS"]
}

Param_Default_Dict = {
    "dt": None,
    "w": None,
    "discount_rate": None,
    "annual_co2_limit": None,
    "co2_price": 0,
    "opex_cost_energy": 0,
    "opex_cost_power": 0,
    "capex_cost_power": 0,
    "efficiency": 1,
    "technical_lifetime": 100,
    "cap_res_min": 0,
    "cap_res_max": 0,
    "availability_profile": 1,
    "technical_availability": 1,
    "output_profile": None,
    "min_eout": 0,
    "out_frac_min": 0,
    "out_frac_max": 1,
    "in_frac_min": 0,
    "in_frac_max": 1,
    "spec_co2": 0,
    "is_storage": None,
    "c_rate": None,
    "efficiency_charge": 1
}

Output_Index_Dict = {
    "Total_annual_co2_emission": ["Y"],
    "Cap_new": ["CS", "Y"],
    "Cap_active": ["CS", "Y"],
    "Cap_res": ["CS", "Y"],
    "Eouttot": ["CS", "Y"],
    "Eintot": ["CS", "Y"],
    "E_storage_level_max": ["CS", "Y"],
    "Eouttime": ["CS", "Y", "T"],
    "Eintime": ["CS", "Y", "T"],
    "Pin": ["CS", "Y", "T"],
    "Pout": ["CS", "Y", "T"],
    "E_storage_level": ["CS", "Y", "T"],
    "Enetgen": ["CO", "Y", "T"],
    "Enetcons": ["CO", "Y", "T"],
    "OPEX": [],
    "CAPEX": [],
    "TOTEX": []
}

